spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/woonstel?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
logging:
  level:
    com.frnz7.restSpring: DEBUG